# Use NGINX as the base image
FROM nginx

# Copy the nginx.conf file to the appropriate location
COPY nginx.conf /etc/nginx/nginx.conf 

# Remove the default NGINX configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Expose port 80 for incoming HTTP traffic
EXPOSE 80
